language: php
php:
  - nightly
  - hhvm
  - 7.0
  - 5.6

sudo: false


before_script:
  - composer install --dev --no-interaction

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

script:
  - ./vendor/bin/phpunit -v --configuration phpunit.xml
